spring.application.name=server
spring.mongodb.uri=mongodb+srv://asiribtennakoon_db_user:YPs4oDKbsip9iUGw@cluster0.flyswrv.mongodb.net/smart_campus_db?retryWrites=true&w=majority

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email