import { Settings, Wrench, GraduationCap, BookOpen } from "lucide-react";

export const portals = [
  {
    id: "admin",
    label: "Admin",
    fullLabel: "Administrator",
    icon: Settings,
    emoji: "🛡️",
    description: "Full system control",
    accentColor: "#1E40AF",
    accentLight: "#EFF6FF",
    accentDark: "#1E3A8A",
    leftGradient: "linear-gradient(150deg, #060D1F 0%, #0F1E4A 45%, #1E3A8A 100%)",
    leftGradientFrom: "#060D1F",
    leftGradientTo: "#1E3A8A",
    badgeBg: "rgba(30,64,175,0.2)",
    badgeText: "#93C5FD",
    isPrivileged: true,
    features: [
      "Manage all users & permissions",
      "Full system configuration",
      "Asset & booking oversight",
      "Access audit logs & reports",
    ],
  },
  {
    id: "technician",
    label: "Technician",
    fullLabel: "Technician",
    icon: Wrench,
    emoji: "🔧",
    description: "Asset & maintenance",
    accentColor: "#334155",
    accentLight: "#F1F5F9",
    accentDark: "#1E293B",
    leftGradient: "linear-gradient(150deg, #050A14 0%, #0F172A 45%, #1E293B 100%)",
    leftGradientFrom: "#050A14",
    leftGradientTo: "#1E293B",
    badgeBg: "rgba(51,65,85,0.35)",
    badgeText: "#94A3B8",
    isPrivileged: true,
    features: [
      "Update asset availability",
      "Log maintenance tasks",
      "View booking schedules",
      "Flag & report asset issues",
    ],
  },
  {
    id: "student",
    label: "Student",
    fullLabel: "Student",
    icon: GraduationCap,
    emoji: "🎓",
    description: "University student",
    accentColor: "#059669",
    accentLight: "#ECFDF5",
    accentDark: "#065F46",
    leftGradient: "linear-gradient(150deg, #022C22 0%, #064E3B 45%, #065F46 100%)",
    leftGradientFrom: "#022C22",
    leftGradientTo: "#065F46",
    badgeBg: "rgba(5,150,105,0.2)",
    badgeText: "#6EE7B7",
    isPrivileged: false,
    features: [
      "Book study spaces & labs",
      "Reserve equipment easily",
      "Track booking status",
      "View campus schedules",
    ],
  },
  {
    id: "lecturer",
    label: "Lecturer",
    fullLabel: "Lecturer / Tutor",
    icon: BookOpen,
    emoji: "👩‍🏫",
    description: "Faculty / Tutor",
    accentColor: "#B45309",
    accentLight: "#FFFBEB",
    accentDark: "#92400E",
    leftGradient: "linear-gradient(150deg, #1C0A00 0%, #451A03 45%, #78350F 100%)",
    leftGradientFrom: "#1C0A00",
    leftGradientTo: "#78350F",
    badgeBg: "rgba(180,83,9,0.2)",
    badgeText: "#FCD34D",
    isPrivileged: false,
    features: [
      "Reserve classrooms & labs",
      "Priority booking access",
      "Schedule recurring sessions",
      "Manage class resources",
    ],
  },
];